language: node_js
cache: yarn
node_js:
- '6'
- '6.1'
after_success:
- npm run test:cover:travis
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIEMAU7JMW5XYN5EQ
  secret_access_key:
    secure: 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
  region: us-west-2
  bucket: hacko-transportation-staging
  skip_cleanup: true
  local_dir: build
